services:
  backend:
    build:
      context: ./backend
    ports:
      - "9004:9004"
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "9003:9003"
    depends_on:
      - backend
  auth:
    build:
      context: ./auth
    ports:
      - "9002:9002"
    depends_on:
      - backend
  notfound:
    build:
      context: ./notfound
    ports:
      - "9001:9001"
    depends_on:
      - backend
  orchestrator:
    build:
      context: ./orchestrator
    ports:
      - "9000:9000"
    depends_on:
      - backend
      - dashboard
      - auth
      - notfound
